version: "3.6"

networks:
  transcendence:
    driver: bridge

volumes:
  voldb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/db_files/
  volnest:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/

services:
    nestjs:
      container_name: nestjs
      build: ./docker/
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOST: postgres_db
        DATABASE_URL: postgres_db://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:${POSTGRES_PORT}/db
        PORT: $PORT
      volumes:
        - volnest:/nest/
      ports:
        - ${PORT}:${PORT}
      networks:
        - transcendence
      depends_on:
        - postgres_db
      restart: always

    postgres_db:
      container_name: postgres_db
      image: postgres
      volumes:
      - voldb:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ports:
        - 5432:5432
      networks:
        - transcendence
      restart: always