version: "3.6"

networks:
  transcendence:
    driver: bridge

volumes:
  voldb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/db_files/
  volnest:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/

services:
    postgres_db:
      container_name: postgres_db
      image: postgres
      volumes:
      - voldb:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      networks:
        - transcendence
      restart: always

    nestjs:
      container_name: nestjs
      build: ./docker/backend
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOST: postgres_db
        PORT: $PORT
        CHAT_PORT: $CHAT_PORT
        GAME_PORT: $GAME_PORT
        FORTYTWO_APP_ID: $FORTYTWO_APP_ID
        FORTYTWO_APP_SECRET: $FORTYTWO_APP_SECRET
        FORTYTWO_CALLBACK_URL: $FORTYTWO_CALLBACK_URL
        JWT_SECRET: $JWT_SECRET
        JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      volumes:
      - volnest:/nest/
      ports:
      - ${PORT}:${PORT}
      - ${CHAT_PORT}:${CHAT_PORT}
      - ${GAME_PORT}:${GAME_PORT}
      networks:
      - transcendence
      depends_on:
      - postgres_db
      restart: always
