version: "3.6"

networks:
  inception:
    driver: bridge

volumes:
  voldb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/doreshev/data/mysql
  volwp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/doreshev/data/html

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    networks:
      - inception
    volumes:
      - volwp:/var/www/
    ports:
      - "443:443"
    depends_on:
      - grafana
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: $DB_NAME
        DB_ROOT: $DB_ROOT
        DB_PASS: $DB_PASS
        DB_USER: $DB_USER
    networks:
     - inception
    volumes:
      - voldb:/var/lib/mysql/
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    environment:
      EVAL_PASS: $EVAL_PASS
      WP_ADMIN: $WP_ADMIN
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      WP_PASS: $WP_PASS
      DOMAIN: $DOMAIN
      EMAIL: $EMAIL
      TITLE: $TITLE
    networks:
      - inception
    volumes:
      - volwp:/var/www/
    depends_on:
      - mariadb
      - redis
      - adminer
    restart: on-failure

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    networks:
      - inception
    restart: on-failure

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp/
      dockerfile: Dockerfile
      args:
        FTP_USER: $FTP_USER
        FTP_PASS: $FTP_PASS
    networks:
      - inception
    volumes:
      - volwp:/var/www/
    depends_on:
      - wordpress
    ports:
      - "21:21"
    restart: on-failure
  
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    networks:
      - inception
    volumes:
      - volwp:/var/www/
    depends_on:
      - mariadb
    restart: on-failure
  
  website:
    container_name: website
    build: ./requirements/bonus/website/
    ports:
      - "80:80"
    restart: on-failure
  
  grafana:
    container_name: grafana
    build: ./requirements/bonus/grafana/
    environment:
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_DATABASE_TYPE: $DP_HOST
      GF_DATABASE_NAME: $DB_NAME
      GF_DATABASE_USER: $DB_USER
      GF_DATABASE_PASSWORD: $DB_PASS
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "3000:3000"
    restart: on-failure